# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T12:43:30+00:00

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, Field, RootModel, constr


class Double(RootModel[float]):
    root: float


class ISO8601Timestamp(RootModel[str]):
    root: str


class Long(RootModel[int]):
    root: int


class MapOfStringToNumber(RootModel[Optional[Dict[str, Double]]]):
    root: Optional[Dict[str, Double]] = None


class String(RootModel[str]):
    root: str


class String0to1000Chars(RootModel[constr(min_length=0, max_length=1000)]):
    root: constr(min_length=0, max_length=1000)


class String10Chars(RootModel[constr(min_length=1, max_length=10)]):
    root: constr(min_length=1, max_length=10)


class String50Chars(RootModel[constr(min_length=1, max_length=50)]):
    root: constr(min_length=1, max_length=50)


class BadRequestException(BaseModel):
    message: Optional[String] = None


class MapOfStringToString(RootModel[Optional[Dict[str, String0to1000Chars]]]):
    root: Optional[Dict[str, String0to1000Chars]] = None


class Session(BaseModel):
    duration: Optional[Long] = None
    id: Optional[String50Chars] = None
    startTimestamp: Optional[ISO8601Timestamp] = None
    stopTimestamp: Optional[ISO8601Timestamp] = None


class Event(BaseModel):
    attributes: Optional[MapOfStringToString] = None
    eventType: String50Chars
    metrics: Optional[MapOfStringToNumber] = None
    session: Optional[Session] = None
    timestamp: ISO8601Timestamp
    version: Optional[String10Chars] = None


class EventListDefinition(RootModel[List[Event]]):
    root: List[Event]


class PutEventsInput(BaseModel):
    events: EventListDefinition


class Field20140605EventsXAmzClientContextPostRequest(BaseModel):
    events: List[Event] = Field(..., description='An array of Event JSON objects')
